config/routes.rb
Rails.application.routes.draw do
  get "/scheduling" => redirect("http://52.53.248.236/VirtualEMS/Login.aspx")
  namespace :admin do
    resources :users
    resources :businesses

    root to: "users#index"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  if Clearance.configuration.allow_sign_up?
    get "/sign_up" => "clearance/users#new", as: "sign_up"
  else
    get "/sign_up" => "home#show"
  end
  root 'home#show'

  resource :home, controller: :home
  resources :events, only: [:index, :show]
  resources :newsletters, only: [:create]
  get ':page' => 'pages#show'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/views/home/_businesses.html.haml
.row.businesses.clearfix
  %h6.secondary Our Businesses
  - businesses.each_with_index do |b, i|
    - klass = i == businesses.length - 1 ? 'end' : ''
    .float-left{class: klass}
      = image_tag "businesses/#{b[:logo]}", "data-tooltip aria-haspopup" => "true","class" => "has-tip","data-disable-hover" => "false","tabindex" => "1","title" => "#{b[:name]}"

app/views/home/show.html.haml
.homepage
  .hero
    .image-callout
      = image_tag "home/rectangle.svg"
      .text
        .responsive-typography.h1 La Cocina
        .sub-header.responsive-typography.h3 Cultivating food entrepreneurs
        .cta
          = link_to 'Donate Once', '/donate', class: 'hollow dark-background button responsive'
          = link_to 'Donate Monthly', '/donate_monthly', class: 'hollow dark-background button responsive'
    = responsive_image_tag 'home/home.jpg'

  .row.call-to-action-boxes
    .medium-4.columns.text-center
      = image_tag 'icons/calendar.svg'
      %h4 La Cocina Events
      %p Eat, laugh and learn something new.
      = link_to 'See our events', events_path, class: 'button'
    .medium-4.columns.text-center
      = image_tag 'icons/support.svg'
      %h4 Get Involved
      %p Be part of the movement.
      = link_to 'Get Involved', '/volunteer', class: 'button'
    .medium-4.columns.text-center
      = image_tag 'icons/gift.svg'
      %h4 La Cocina Gift Boxes
      %p Make a difference.
      = link_to 'Buy a gift box', 'https://la-cocina-sf-store.myshopify.com', class: 'button'

  .story-banner.testimonial.show-for-medium
    = responsive_image_tag "home/bini.jpg"
    .text
      .quote.responsive-typography.h3 "I thank god every day for La Cocina... but it was momos that saved my life."
      .responsive-typography.h4 Binita Pradhan, Bini's Kitchen
      .cta= link_to "READ BINITA’S STORY", "http://www.sfgate.com/food/eatup/article/Bini-s-Kitchen-cooks-up-Nepalese-charm-in-6738213.php", class: "hollow button", target: "_blank"

  .row.who-we-work-with
    %h2 WHO WE WORK WITH

    .large-6.columns
      .business-owners
        .col.number-of-business-owners 33

        .col
          .header Business Owners in 2015
          .sub-header At La Cocina, women and people of color are owners and leaders.

    .large-6.columns.pie-charts
      = render partial: 'partials/pie_chart', locals: { percentage: "94", caption: "Women" }
      = render partial: 'partials/pie_chart', locals: { percentage: "70", caption: "Parents" }
      = render partial: 'partials/pie_chart', locals: { percentage: "60", caption: "Immigrants" }
      = render partial: 'partials/pie_chart', locals: { percentage: "91", caption: "People of color" }


  .text-center
    %h2 FIND OUR BUSINESSES AROUND YOU
    .image.hide-for-medium
      = link_to 'http://www.google.com/maps/d/embed?mid=1OcGetCOiKBlGyYudjmBuRQSnOC0', class: 'map-link' do
        = responsive_image_tag 'map.png'
    .image.show-for-medium
      = responsive_image_tag 'map.png'
      .large-4.large-offset-4.columns.overlay.bottom-center
        = link_to 'View our businesses on the map', 'http://www.google.com/maps/d/embed?mid=1OcGetCOiKBlGyYudjmBuRQSnOC0', class: 'expanded button skinny', target: '_blank'


  .row.text-center
    %h2.secondary Our Businesses
    = render partial: 'partials/businesses', locals: { businesses: featured_businesses }