config/routes.rb
Rails.application.routes.draw do
  get "/scheduling" => redirect("http://52.53.248.236/VirtualEMS/Login.aspx")
  namespace :admin do
    resources :users
    resources :businesses

    root to: "users#index"
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  if Clearance.configuration.allow_sign_up?
    get "/sign_up" => "clearance/users#new", as: "sign_up"
  else
    get "/sign_up" => "home#show"
  end
  root 'home#show'

  resource :home, controller: :home
  resources :events, only: [:index, :show]
  resources :newsletters, only: [:create]
  get ':page' => 'pages#show'
end

app/views/layouts/_footer.html.haml
%footer.footer
  .header Stay Connected

  .newsletter-sign-up
    = form_for :newsletter, url: newsletters_path do |form|
      = form.label 'Sign in with your email address below to receive our newsletter.'

      .input-button-combo
        = form.text_field :email, type: 'email'
        = form.submit 'Sign Up', class: 'button'

    .social-media-icons
      = render partial: 'layouts/social_media'

  .made-by MADE BY VOLUNTEERS 2016

app/views/layouts/_header.html.haml
%header
  .row.heading
    .hide-for-large
      .top-bar.mobile-bar{'data-responsive-toggle': 'offCanvasMenu', 'data-hide-for': 'large'}
        %button.menu-icon{'type': 'button', 'data-toggle': 'offCanvasMenu'}
        .mobile-bar-title
          = link_to root_path do
            = image_tag 'logo.png'

    .show-for-large
      %nav#top-menu.top-bar{'data-topbar': true, role: 'navigation'}
        .top-bar-title.logo-size
          = link_to root_path do
            = image_tag 'logo.png'

        .social-media-icons
          = render partial: 'layouts/social_media'
          = link_to 'Donate', '/donate', class: 'button'
          - if signed_in?
            = link_to "Sign Out", sign_out_path, method: :delete

        %ul.dropdown.menu{'data-dropdown-menu': true}
          - menu_items.each do |menu_item|
            - klass = menu_item[:submenu] ? 'is-dropdown-submenu-parent' : ''
            %li{class: klass}
              = link_to menu_item[:name], menu_item[:url]
              - if menu_item[:submenu]
                %ul.menu.submenu.vertical{'data-submenu': true}
                  - menu_item[:submenu].each do |submenu_item|
                    %li
                      = link_to submenu_item[:name], submenu_item[:url]

app/views/layouts/_mobile_menu.html.haml
#offCanvasMenu.off-canvas.position-left{'data-off-canvas': true}
  %button.close-button{'aria-label': 'Close menu', 'type': 'button', 'data-close': ""}
    %span{'aria-hidden': true} &times;
  %ul.vertical.menu{'data-drilldown': ""}
    - menu_items.each do |menu_item|
      - klass = menu_item[:submenu] ? 'has-submenu' : ''
      %li{class: klass}
        = link_to menu_item[:name], menu_item[:url]
        - if menu_item[:submenu]
          %ul.menu.left-submenu.vertical{'data-submenu': true}
            - menu_item[:submenu].each do |submenu_item|
              %li
                = link_to submenu_item[:name], submenu_item[:url]
    %li
      = link_to 'Donate', '/donate', class: 'button'

app/views/layouts/_social_media.html.haml
- social_media_links.each do |site|
  .social-media-icon
    = link_to site[:link], target: "_blank" do
      = inline_svg "icons/" + site[:icon]

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "La Cocina | San Francisco Incubator Kitchen"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

    -# ADD GOOGLE ANALYTICS TRACKING
    :javascript
      var ga_key ="#{ENV['GA_KEY']}";
      if (ga_key) {
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', ga_key, 'auto');
        ga('send', 'pageview');
      }

  %body
    .off-canvas-wrapper
      .off-canvas-wrapper-inner{'data-off-canvas-wrapper': true}
        = render partial: 'layouts/mobile_menu'
        .off-canvas-content{'data-off-canvas-content': true}
          = render partial: 'layouts/header'
          = yield
          = render partial: 'layouts/footer'
          #fb-root
          :javascript
            (function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));

app/views/layouts/login.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "La Cocina | San Francisco Incubator Kitchen"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

    -# ADD GOOGLE ANALYTICS TRACKING
    :javascript
      var ga_key ="#{ENV['GA_KEY']}";
      if (ga_key) {
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', ga_key, 'auto');
        ga('send', 'pageview');
      }

  %body
    = render partial: 'layouts/header'
    .row
      #flash
        - flash.each do |key, value|
          %div{id: "flash_#{key}"}= value
    .row
      .small-6.small-centered.columns
        = yield
    = render partial: 'layouts/footer'